language: cpp

before_install:
   - gem install package_clou

install:
    - sudo apt-get install -y libreadline-dev libconfig-dev libssl-dev lua5.2 liblua5.2-dev libevent-dev libjansson-dev libpython-dev make libgcrypt20 libgcrypt20-dev

script:
    - bash compile.sh

script:
    - package_cloud push deadda7a/telegram-cli/ubuntu/xenial ./telegram-cli.deb
